### ISSUE TITLE
AttributeError: 'Metrics' object has no attribute 'validation_data'

### ISSUE THREAD

**Issue by learnercat** [ArmandDS/lexical_simplification_bert#1]
Hi! When I tried to run this Lexical_Simplification_with_BERT.ipynb on my machine, I've got an error after model fitting step:

`history = model.fit(train_words_padded, np.array(train_binary_padded_categorical), batch_size=2, 
                    epochs=3, validation_data = (test_words_padded, np.array(test_binary_padded_categorical)), 
                    verbose=1, callbacks=[metrics])`
`Epoch 1/3
994/994 [==============================] - ETA: 0s - loss: 0.0598 - accuracy: 0.9755`

AttributeError                            Traceback (most recent call last)
<ipython-input-44-78c4c4cc896d> in <module>
----> 1 history = model.fit(train_words_padded, np.array(train_binary_padded_categorical), batch_size=2, 
      2                     epochs=3, validation_data = (test_words_padded, np.array(test_binary_padded_categorical)),
      3                     verbose=1, callbacks=[metrics])

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1135           epoch_logs.update(val_logs)
   1136 
-> 1137         callbacks.on_epoch_end(epoch, epoch_logs)
   1138         training_logs = epoch_logs
   1139         if self.stop_training:

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    414         if numpy_logs is None:  # Only convert once.
    415           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
--> 416         callback.on_epoch_end(epoch, numpy_logs)
    417 
    418   def on_train_batch_begin(self, batch, logs=None):

<ipython-input-42-96ad0e74b8ea> in on_epoch_end(self, batch, logs)
      7 
      8     def on_epoch_end(self, batch, logs={}):
----> 9         predict = np.asarray(self.model.predict(self.validation_data[0]))
     10         targ = self.validation_data[1]
     11         targ = np.array(targ)

AttributeError: 'Metrics' object has no attribute 'validation_data'

Please help. Thanks in advance.

**Comment by ArmandDS** [comment]
Hi 
Thank you for reading, I fixed now, please check it again, however that model is only for the complex word identification part, and only for demo you can train your own model for this part if you want.
Best
